---
title: "Visualization"
subtitle: "Part II"
output: github_document
---

```{r setup}
library(tidyverse)
library(patchwork)
```

## Load the weather data


```{r}
library(p8105.datasets)
data("weather_df")
```

## Remember this plot..?

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5)
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5)+
labs(
  title = "Temperature plot",
  x = "Minimum daily temperature (C)",
  y = "Maximum daily temperature (C)",
  caption = "Data from the rnoaa package; temperatures in 2017."
)
```

## Scales

Start with the same plot

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5)+
labs(
  title = "Temperature plot",
  x = "Minimum daily temperature (C)",
  y = "Maximum daily temperature (C)",
  caption = "Data from the rnoaa package; temperatures in 2017."
) +
scale_x_continuous(
  breaks = c(-15, 0 , 15),
  labels = c("-15 C", "0 C", "15 C")
)+
scale_y_continuous(
  position= "right"
)
```

Look at color scales

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5)+
labs(
  title = "Temperature plot",
  x = "Minimum daily temperature (C)",
  y = "Maximum daily temperature (C)",
  caption = "Data from the rnoaa package; temperatures in 2017."
) +
   viridis::scale_color_viridis(
     name = "Location",
     discrete = TRUE)
```

**scale_color_hue(
  name = "Location",
  h = c(100,300))** to change color and name of legend

## Themes- doesn't depend on data

Shift the Legend.

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5)+
labs(
  title = "Temperature plot",
  x = "Minimum daily temperature (C)",
  y = "Maximum daily temperature (C)",
  caption = "Data from the rnoaa package; temperatures in 2017."
) +
   viridis::scale_color_viridis(
     name = "Location",
     discrete = TRUE) +
  theme(legend.position = "bottom")
```

Change the overall theme.
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5)+
labs(
  title = "Temperature plot",
  x = "Minimum daily temperature (C)",
  y = "Maximum daily temperature (C)",
  caption = "Data from the rnoaa package; temperatures in 2017."
) +
   viridis::scale_color_viridis(
     name = "Location",
     discrete = TRUE) +
   theme_minimal() +
  theme(legend.position = "bottom")
```

##Setting options
copy and paste in r markdown document in beginning to set the visual
```{r eval = FALSE}
library(tidyverse)

knittr::opts_chunk$set(
    fig.width = .6,
    fig. asp = .6,
    out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.postion = "bottom"))

options(
  ggplot2.continuous.colour = "viridis"
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


